<?php

return [
    // Page Headers
    'hr_reports' => 'HR Reports',
    'generate_report' => 'Generate Report',
    
    // Report Types
    'employee_report' => 'Employee Report',
    'attendance_report' => 'Attendance Report',
    'leave_report' => 'Leave Report',
    'payroll_report' => 'Payroll Report',
    'turnover_report' => 'Turnover Report',
    'recruitment_report' => 'Recruitment Report',
    'training_report' => 'Training Report',
    'performance_report' => 'Performance Report',
    'custom_report' => 'Custom Report',
    
    // Form Fields and Labels
    'report_type' => 'Report Type',
    'select_report_type' => 'Select Report Type',
    'start_date' => 'Start Date',
    'end_date' => 'End Date',
    'select_date_range' => 'Select Date Range',
    'department' => 'Department',
    'select_department' => 'Select Department',
    'all_departments' => 'All Departments',
    'employee' => 'Employee',
    'select_employee' => 'Select Employee',
    'all_employees' => 'All Employees',
    'status' => 'Status',
    'select_status' => 'Select Status',
    'all_statuses' => 'All Statuses',
    'group_by' => 'Group By',
    'select_grouping' => 'Select Grouping',
    'format' => 'Format',
    'select_format' => 'Select Format',
    
    // Report Formats
    'pdf' => 'PDF',
    'excel' => 'Excel',
    'csv' => 'CSV',
    'html' => 'HTML',
    
    // Group By Options
    'none' => 'None',
    'department' => 'Department',
    'position' => 'Position',
    'status' => 'Status',
    'date' => 'Date',
    'month' => 'Month',
    'year' => 'Year',
    
    // Button Labels
    'generate' => 'Generate',
    'reset' => 'Reset',
    'export' => 'Export',
    'print' => 'Print',
    'save' => 'Save',
    'close' => 'Close',
    
    // Report Elements
    'report_title' => 'Report Title',
    'report_date' => 'Report Date',
    'generated_by' => 'Generated By',
    'filters_applied' => 'Filters Applied',
    'no_filters' => 'No Filters Applied',
    'period' => 'Period',
    'summary' => 'Summary',
    'details' => 'Details',
    'total' => 'Total',
    'average' => 'Average',
    'minimum' => 'Minimum',
    'maximum' => 'Maximum',
    
    // Notifications
    'report_generated' => 'Report generated successfully',
    'error_occurred' => 'An error occurred while generating the report',
    
    // Empty States
    'no_data_found' => 'No data found for the selected criteria',
    'adjust_filters' => 'Please adjust your filters and try again',
    
    // Additional Report-Specific Labels
    'total_employees' => 'Total Employees',
    'active_employees' => 'Active Employees',
    'inactive_employees' => 'Inactive Employees',
    'new_hires' => 'New Hires',
    'terminations' => 'Terminations',
    'turnover_rate' => 'Turnover Rate',
    'attendance_rate' => 'Attendance Rate',
    'leave_balance' => 'Leave Balance',
    'leave_utilization' => 'Leave Utilization',
    'payroll_summary' => 'Payroll Summary',
    'total_salaries' => 'Total Salaries',
    'total_deductions' => 'Total Deductions',
    'total_net_pay' => 'Total Net Pay',
];
